'use client'

import { useState } from 'react'
import { ArrowRight, ArrowUpRight, BarChart3, Building2, CheckCircle2, ChevronDown, CircleDollarSign, FileCheck2, LineChart, LockKeyhole, ShieldCheck, Sparkles, Users, WalletCards } from 'lucide-react'
import './FractionalPage.css'

const investorSteps = [['01','Discover','Explore curated commercial, residential, logistics, and development opportunities.'],['02','Verify','Review the property memo, financial model, title checks, and risk disclosures.'],['03','Invest','Reserve units from ₹35,000 with a clear ownership and fee structure.'],['04','Earn','Receive your share of eligible rental distributions and track P&L live.'],['05','Exit','Hold for appreciation or explore available liquidity windows on the marketplace.']]
const developerSteps = [['01','List','Present an investment-ready asset to a network of verified investors.'],['02','Structure','Define unit size, pricing, projected distributions, and ownership terms.'],['03','Raise','Access a wider pool of capital without losing visibility or control.'],['04','Report','Share occupancy, project, and financial updates through one trusted workspace.'],['05','Grow','Build a repeat investor base for your next high-quality opportunity.']]
const benefits = [['₹','Start smaller','Participate in assets that once required a balance sheet and a boardroom.'],[<LineChart size={22} key="line"/>,'Built for income','See projected yield, distribution history, occupancy, and costs before you invest.'],[<BarChart3 size={22} key="bar"/>,'Diversify simply','Spread capital across locations, asset classes, tenants, and investment horizons.'],[<ShieldCheck size={22} key="shield"/>,'Vetted opportunities','Every listing is supported by structured diligence, documentation, and disclosures.'],[<Users size={22} key="users"/>,'Professional management','Developers and operators keep the asset moving while you track the outcome.'],[<WalletCards size={22} key="wallet"/>,'Designed for liquidity','When eligible, discover potential buyers and liquidity events through the marketplace.']]
const faqs = [['Is fractional ownership the same as a REIT?','No. The legal structure, rights, liquidity, and regulatory treatment can differ by opportunity. Always review the individual property documents and disclosures before investing.'],['How do I earn from a property?','Eligible investors may receive a proportional share of net rental distributions, while the unit value can move with the underlying property and market conditions.'],['Can my investment lose value?','Yes. Property prices, occupancy, interest rates, costs, and execution can affect returns. Example figures on this page are illustrative, not guaranteed.'],['What does Milestono verify?','The platform is designed to present property documentation, financial assumptions, ownership terms, operating updates, and relevant risk disclosures in one place.'],['How do developers benefit?','Developers can reach a broader investor base, structure transparent unit offerings, and maintain a central reporting channel after the raise.']]

function Chart({ mode }) { return <div className="fractional-page__chart-wrap"><div className="fractional-page__chart-labels"><span>₹60k</span><span>₹45k</span><span>₹30k</span><span>₹15k</span></div><svg className="fractional-page__chart" viewBox="0 0 720 270" role="img" aria-label={mode === 'value' ? 'Illustrative unit value rising from thirty thousand to forty eight thousand rupees' : 'Illustrative annual yield trend between seven and nine percent'} preserveAspectRatio="none"><path className="fractional-grid" d="M0 32H720M0 100H720M0 168H720M0 236H720" />{mode === 'value' ? <><path className="fractional-area" d="M0 216C70 220 86 197 143 205S210 166 265 180S331 136 384 154S458 102 510 119S589 69 642 85S688 55 720 35V270H0Z"/><path className="fractional-line" d="M0 216C70 220 86 197 143 205S210 166 265 180S331 136 384 154S458 102 510 119S589 69 642 85S688 55 720 35"/><circle className="fractional-chart-dot" cx="720" cy="35" r="7"/></> : <><path className="fractional-area fractional-area--green" d="M0 162C70 172 94 145 145 158S223 116 271 131S342 125 391 133S452 85 503 108S580 77 629 90S681 60 720 65V270H0Z"/><path className="fractional-line fractional-line--green" d="M0 162C70 172 94 145 145 158S223 116 271 131S342 125 391 133S452 85 503 108S580 77 629 90S681 60 720 65"/><circle className="fractional-chart-dot fractional-chart-dot--green" cx="720" cy="65" r="7"/></>}</svg><div className="fractional-page__chart-months"><span>Jan</span><span>Mar</span><span>May</span><span>Jul</span><span>Sep</span><span>Nov</span></div></div> }

function Flow({ title, intro, steps, developer = false }) { return <section className="fractional-page__section fractional-flow"><div className="fractional-page__section-head"><span className="fractional-page__eyebrow">{developer ? 'For developers' : 'For investors'}</span><h2>{title}</h2><p>{intro}</p></div><div className="fractional-flow__grid">{steps.map(([number, name, text]) => <article key={name} className="fractional-flow__item"><span>{number}</span><div><h3>{name}</h3><p>{text}</p></div></article>)}</div></section> }

export default function FractionalPage() {
  const [mode, setMode] = useState('value')
  const [openFaq, setOpenFaq] = useState(0)
  return <main className="fractional-page">
    <header className="fractional-page__nav"><a className="fractional-page__brand" href="/"><span><Building2 size={18}/></span><b>Milestono</b><small>Investors</small></a><nav><a href="#how-it-works">How it works</a><a href="#economics">Unit economics</a><a href="#trust">Trust & risk</a></nav><a className="fractional-page__nav-cta" href="/auth/login">Start exploring <ArrowRight size={15}/></a></header>
    <section className="fractional-page__hero"><div className="fractional-page__hero-copy"><span className="fractional-page__eyebrow"><Sparkles size={14}/> Real estate, made investable</span><h1>Own a fractional unit.<br/><em>Access real estate.</em></h1><p>Milestono brings the clarity of a modern investment platform to property investing. Explore curated opportunities, purchase fractional units representing a defined share of an asset, and follow every rupee.</p><div className="fractional-page__actions"><a className="fractional-button fractional-button--primary" href="/auth/login">Start investing <ArrowUpRight size={16}/></a><a className="fractional-button fractional-button--ghost" href="#how-it-works">See how it works <ArrowRight size={16}/></a></div><div className="fractional-page__trust-row"><span><ShieldCheck size={17}/> Structured disclosures</span><span><LockKeyhole size={17}/> Secure ownership records</span><span><FileCheck2 size={17}/> Data-led decisions</span></div></div><div className="fractional-page__dashboard" aria-label="Illustrative portfolio value dashboard"><div className="fractional-page__dash-top"><span>Portfolio value <small>Illustrative</small></span><span className="fractional-page__dash-menu">•••</span></div><strong>₹12,84,260</strong><div className="fractional-page__dash-change"><span>+₹1,46,820</span><b>+12.92%</b><small>since invested</small></div><svg viewBox="0 0 440 130" preserveAspectRatio="none" aria-hidden="true"><path d="M0 112C43 111 55 88 93 97S139 69 177 79S220 63 255 67S298 38 333 48S373 26 404 32S424 17 440 8V130H0Z"/><path className="fractional-dash-line" d="M0 112C43 111 55 88 93 97S139 69 177 79S220 63 255 67S298 38 333 48S373 26 404 32S424 17 440 8"/></svg><div className="fractional-page__dash-stats"><span><small>Annual yield</small><b>8.6%</b></span><span><small>Properties</small><b>04</b></span><span><small>Monthly income</small><b>₹9,240</b></span></div><div className="fractional-page__asset"><span><Building2 size={17}/><span><b>Harbour One, Mumbai</b><small>Commercial office · 12 units</small></span></span><b>+14.8%</b></div></div></section>
    <section className="fractional-page__proof"><div><strong>₹140Cr+</strong><span>assets represented</span></div><div><strong>12,450</strong><span>active investors</span></div><div><strong>48</strong><span>curated properties</span></div><div><strong>11.4%</strong><span>illustrative average yield</span></div></section>
    <Flow title="A better way to enter real estate" intro="From your first watchlist to your first distribution, Milestono keeps the journey clear, documented, and in your hands." steps={investorSteps}/>
    <section className="fractional-page__section fractional-benefits"><div className="fractional-page__section-head"><span className="fractional-page__eyebrow">Why fractional</span><h2>Real estate benefits, without the old friction.</h2><p>Build exposure with more flexibility, more context, and a lower starting point than traditional property ownership.</p></div><div className="fractional-benefits__grid">{benefits.map(([icon,title,text]) => <article key={title}><span className="fractional-benefit-icon">{icon}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="fractional-page__section fractional-performance"><div className="fractional-page__section-head"><span className="fractional-page__eyebrow">Illustrative unit intelligence</span><h2>See the story behind every number.</h2><p>Understand how an illustrative unit can move over time. Switch views to see potential capital movement or yield performance.</p></div><div className="fractional-performance__card"><div className="fractional-performance__top"><div><span className="fractional-page__eyebrow">Harbour One · Unit 08</span><h3>{mode === 'value' ? 'Unit value' : 'Rental yield'}</h3><strong>{mode === 'value' ? '₹48,260' : '8.6%'}</strong><span className="fractional-gain"><ArrowUpRight size={14}/> {mode === 'value' ? '+12.84%' : '+1.4%'} this year</span></div><div className="fractional-toggle" role="group" aria-label="Chart view"><button className={mode === 'value' ? 'is-active' : ''} onClick={() => setMode('value')}>Value</button><button className={mode === 'yield' ? 'is-active' : ''} onClick={() => setMode('yield')}>Yield</button></div></div><Chart mode={mode}/><div className="fractional-performance__foot"><span><i className="fractional-dot fractional-dot--blue"/> Market value</span><span><i className="fractional-dot fractional-dot--green"/> Distributions</span><small>Example figures only</small></div></div></section>
    <Flow title="A capital partner developers can trust" intro="Turn a high-quality property into an investable opportunity with structure, visibility, and a stronger relationship with your capital base." steps={developerSteps} developer/>
    <section id="economics" className="fractional-page__section fractional-economics"><div className="fractional-page__section-head"><span className="fractional-page__eyebrow">Fractional unit economics</span><h2>Know what your unit represents.</h2><p>Every opportunity should make ownership, income, costs, and scenarios easier to understand before capital moves.</p></div><div className="fractional-economics__grid"><div className="fractional-ownership"><div className="fractional-ownership__ring"><span><b>1 / 12</b><small>share of asset</small></span></div><h3>One unit, a real economic interest.</h3><p>Your unit represents a defined share in the opportunity. Rental income and capital movement are shown proportionally after applicable costs.</p><div className="fractional-ownership__legend"><span><i className="fractional-dot fractional-dot--blue"/> Ownership value <b>₹35,000</b></span><span><i className="fractional-dot fractional-dot--green"/> Illustrative income <b>₹3,010</b></span><span><i className="fractional-dot fractional-dot--slate"/> Costs & reserves <b>₹420</b></span></div></div><div className="fractional-table-wrap"><table><caption>Illustrative annual unit scenario</caption><thead><tr><th>Line item</th><th>Per unit</th><th>What it means</th></tr></thead><tbody><tr><td>Starting unit value</td><td>₹35,000</td><td>Illustrative entry value</td></tr><tr><td>Gross rental income</td><td>₹3,600</td><td>Before operating costs</td></tr><tr><td>Operating costs</td><td className="fractional-loss">− ₹590</td><td>Maintenance, vacancy, reserves</td></tr><tr><td>Net distribution</td><td className="fractional-gain">₹3,010</td><td>Potential cash income</td></tr><tr><td>Illustrative capital movement</td><td className="fractional-gain">+ ₹2,450</td><td>Not guaranteed</td></tr></tbody></table></div></div></section>
    <section id="trust" className="fractional-page__section fractional-trust"><div className="fractional-trust__intro"><span className="fractional-page__eyebrow">Trust, before transaction</span><h2>Confidence comes from seeing the whole picture.</h2><p>Milestono is designed to make property investing more understandable, not to remove the risks that come with it.</p></div><div className="fractional-trust__cards"><article><ShieldCheck size={22}/><h3>Structured diligence</h3><p>Review ownership context, project documents, assumptions, and operational details before you commit.</p></article><article><FileCheck2 size={22}/><h3>Transparent reporting</h3><p>Keep distributions, occupancy, valuation signals, and updates in one accessible record.</p></article><article><CircleDollarSign size={22}/><h3>Risk-first language</h3><p>No guaranteed returns. Property markets can fall, income can vary, and liquidity may be limited.</p></article></div><div className="fractional-risk-note"><CheckCircle2 size={18}/><p><b>Important:</b> All performance figures on this page are illustrative and for education only. Investments involve risk. Review the specific legal, financial, tax, and regulatory documents for each opportunity.</p></div></section>
    <section className="fractional-page__section fractional-faq"><div className="fractional-page__section-head"><span className="fractional-page__eyebrow">Questions, answered</span><h2>Start with clarity.</h2></div><div className="fractional-faq__list">{faqs.map(([question,answer], index) => <div className={`fractional-faq__item ${openFaq === index ? 'is-open' : ''}`} key={question}><button onClick={() => setOpenFaq(openFaq === index ? -1 : index)} aria-expanded={openFaq === index}><span>{question}</span><ChevronDown size={18}/></button><div className="fractional-faq__answer"><p>{answer}</p></div></div>)}</div></section>
    <section className="fractional-page__cta"><span className="fractional-page__eyebrow">Your next milestone starts here</span><h2>Make real estate a more intentional part of your portfolio.</h2><p>Explore the marketplace, compare opportunities, and decide with the context you deserve.</p><div className="fractional-page__actions"><a className="fractional-button fractional-button--primary" href="/auth/login">Explore opportunities <ArrowUpRight size={16}/></a><a className="fractional-button fractional-button--light" href="/auth/login">List a property <ArrowRight size={16}/></a></div></section>
  </main>
}
