/**
 * In-memory data store for development / demo.
 * Swap out the exported collections with Firebase/Firestore calls in production.
 */

import { Property, Investment, Transaction, PriceAlert, User } from '@/lib/types'
import { generatePriceHistory } from '@/lib/store/seed'

// ─── PROPERTIES ────────────────────────────────────────────────────────────
export const propertiesStore: Map<string, Property> = new Map()

// ─── INVESTMENTS ───────────────────────────────────────────────────────────
export const investmentsStore: Map<string, Investment> = new Map()

// ─── TRANSACTIONS ──────────────────────────────────────────────────────────
export const transactionsStore: Map<string, Transaction> = new Map()

// ─── PRICE ALERTS ──────────────────────────────────────────────────────────
export const alertsStore: Map<string, PriceAlert> = new Map()

// ─── USERS ─────────────────────────────────────────────────────────────────
export const usersStore: Map<string, User> = new Map()

// ─── WATCHLISTS ────────────────────────────────────────────────────────────
export const watchlistStore: Map<string, string[]> = new Map() // userId → propertyIds[]

let seeded = false

export function ensureSeeded() {
  if (seeded) return
  seeded = true
  seedProperties()
}

function seedProperties() {
  const PROPERTY_DATA: Omit<Property, 'id' | 'marketData' | 'listedAt' | 'lastUpdated'>[] = [
    {
      name: 'Prestige Sunrise Park',
      symbol: 'PRSN',
      location: 'Whitefield',
      address: '14 Whitefield Road',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560066',
      type: 'residential',
      totalUnits: 500,
      unitsAvailable: 183,
      unitPrice: 125000,
      rentalData: { expectedYield: 9.2, occupancyRate: 94, rentalIncome: 48000000 },
      expectedYield: 9.2,
      occupancyRate: 94,
      status: 'active',
      description: 'Premium gated community with 3 BHK apartments in Whitefield tech corridor. RERA registered, OC received.',
      amenities: ['Swimming Pool', 'Gym', 'Clubhouse', 'Security', 'Power Backup'],
      images: [],
      documents: { termsUrl: '/docs/terms.pdf', prospectusUrl: '/docs/prospectus.pdf', riskDisclosureUrl: '/docs/risk.pdf' },
      createdBy: 'developer-1',
    },
    {
      name: 'Godrej BKC Heights',
      symbol: 'GDBK',
      location: 'BKC',
      address: 'G Block, Bandra Kurla Complex',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400051',
      type: 'commercial',
      totalUnits: 800,
      unitsAvailable: 312,
      unitPrice: 285000,
      rentalData: { expectedYield: 7.8, occupancyRate: 97, rentalIncome: 182400000 },
      expectedYield: 7.8,
      occupancyRate: 97,
      status: 'active',
      description: 'Grade A commercial office space in India\'s prime business district. LEED platinum certified.',
      amenities: ['24/7 Security', 'Conference Rooms', 'Cafeteria', 'EV Charging', 'HVAC'],
      images: [],
      documents: { termsUrl: '/docs/terms.pdf', prospectusUrl: '/docs/prospectus.pdf', riskDisclosureUrl: '/docs/risk.pdf' },
      createdBy: 'developer-1',
    },
    {
      name: 'DLF Capital Greens',
      symbol: 'DLCG',
      location: 'Shivaji Marg',
      address: 'Shivaji Marg, Moti Nagar',
      city: 'Delhi',
      state: 'Delhi',
      pincode: '110015',
      type: 'residential',
      totalUnits: 1200,
      unitsAvailable: 445,
      unitPrice: 175000,
      rentalData: { expectedYield: 8.4, occupancyRate: 91, rentalIncome: 176400000 },
      expectedYield: 8.4,
      occupancyRate: 91,
      status: 'active',
      description: 'DLF\'s flagship residential project with world-class amenities across 35 acres.',
      amenities: ['Olympic Pool', 'Spa', 'Tennis Court', 'Jogging Track', 'Kids Zone'],
      images: [],
      documents: { termsUrl: '/docs/terms.pdf', prospectusUrl: '/docs/prospectus.pdf', riskDisclosureUrl: '/docs/risk.pdf' },
      createdBy: 'developer-2',
    },
    {
      name: 'Embassy Tech Village',
      symbol: 'EMTV',
      location: 'Outer Ring Road',
      address: 'Embassy Golf Links Business Park',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560071',
      type: 'commercial',
      totalUnits: 2000,
      unitsAvailable: 890,
      unitPrice: 98000,
      rentalData: { expectedYield: 11.2, occupancyRate: 99, rentalIncome: 219000000 },
      expectedYield: 11.2,
      occupancyRate: 99,
      status: 'active',
      description: 'India\'s largest business park housing global Fortune 500 companies.',
      amenities: ['Helipad', 'Hotel', 'Schools', 'Hospital', 'Retail'],
      images: [],
      documents: { termsUrl: '/docs/terms.pdf', prospectusUrl: '/docs/prospectus.pdf', riskDisclosureUrl: '/docs/risk.pdf' },
      createdBy: 'developer-2',
    },
    {
      name: 'Sobha Dream Acres',
      symbol: 'SBDA',
      location: 'Panathur',
      address: 'Panathur Road, Varthur',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560087',
      type: 'residential',
      totalUnits: 3000,
      unitsAvailable: 1230,
      unitPrice: 68500,
      rentalData: { expectedYield: 8.9, occupancyRate: 88, rentalIncome: 181800000 },
      expectedYield: 8.9,
      occupancyRate: 88,
      status: 'active',
      description: 'Asia\'s largest township project. 81-acre integrated smart city development.',
      amenities: ['Mall', 'Schools', 'Hospital', '5 Clubs', 'Sports Academy'],
      images: [],
      documents: { termsUrl: '/docs/terms.pdf', prospectusUrl: '/docs/prospectus.pdf', riskDisclosureUrl: '/docs/risk.pdf' },
      createdBy: 'developer-1',
    },
    {
      name: 'Phoenix Palassio',
      symbol: 'PHPL',
      location: 'Hazratganj',
      address: 'Sultanpur Road',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      pincode: '226012',
      type: 'commercial',
      totalUnits: 600,
      unitsAvailable: 218,
      unitPrice: 55000,
      rentalData: { expectedYield: 10.5, occupancyRate: 96, rentalIncome: 34650000 },
      expectedYield: 10.5,
      occupancyRate: 96,
      status: 'active',
      description: 'North India\'s largest premium retail and entertainment complex.',
      amenities: ['Multiplex', 'Food Court', 'Gaming Zone', 'Luxury Brands', 'Valet'],
      images: [],
      documents: { termsUrl: '/docs/terms.pdf', prospectusUrl: '/docs/prospectus.pdf', riskDisclosureUrl: '/docs/risk.pdf' },
      createdBy: 'developer-3',
    },
    {
      name: 'Hiranandani Business Park',
      symbol: 'HIBP',
      location: 'Powai',
      address: 'Hiranandani Gardens, Powai',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400076',
      type: 'commercial',
      totalUnits: 750,
      unitsAvailable: 225,
      unitPrice: 320000,
      rentalData: { expectedYield: 8.1, occupancyRate: 98, rentalIncome: 243000000 },
      expectedYield: 8.1,
      occupancyRate: 98,
      status: 'active',
      description: 'Iconic integrated township with premium offices and luxury residences in Mumbai.',
      amenities: ['Business Centre', 'Fine Dining', 'Retail', 'Bank', 'Clinic'],
      images: [],
      documents: { termsUrl: '/docs/terms.pdf', prospectusUrl: '/docs/prospectus.pdf', riskDisclosureUrl: '/docs/risk.pdf' },
      createdBy: 'developer-2',
    },
    {
      name: 'Lodha Palava City',
      symbol: 'LDPA',
      location: 'Dombivali',
      address: 'Palava Phase 2, Dombivali East',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '421204',
      type: 'residential',
      totalUnits: 5000,
      unitsAvailable: 2100,
      unitPrice: 42000,
      rentalData: { expectedYield: 7.6, occupancyRate: 85, rentalIncome: 159600000 },
      expectedYield: 7.6,
      occupancyRate: 85,
      status: 'active',
      description: 'Future-ready smart city built on 4500+ acres with world-class social infrastructure.',
      amenities: ['International School', 'Mall', 'Hospital', 'Sports Complex', 'Tech Hub'],
      images: [],
      documents: { termsUrl: '/docs/terms.pdf', prospectusUrl: '/docs/prospectus.pdf', riskDisclosureUrl: '/docs/risk.pdf' },
      createdBy: 'developer-3',
    },
    {
      name: 'Tata Housing Serein',
      symbol: 'THSR',
      location: 'Thane West',
      address: 'Pokhran Road No. 2',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400610',
      type: 'residential',
      totalUnits: 400,
      unitsAvailable: 142,
      unitPrice: 195000,
      rentalData: { expectedYield: 9.7, occupancyRate: 93, rentalIncome: 75920000 },
      expectedYield: 9.7,
      occupancyRate: 93,
      status: 'active',
      description: 'Luxury residential living with panoramic views of Yeoor Hills.',
      amenities: ['Infinity Pool', 'Sky Lounge', 'Zen Garden', 'Concierge', 'EV Charging'],
      images: [],
      documents: { termsUrl: '/docs/terms.pdf', prospectusUrl: '/docs/prospectus.pdf', riskDisclosureUrl: '/docs/risk.pdf' },
      createdBy: 'developer-1',
    },
    {
      name: 'Brigade Horizon',
      symbol: 'BRHZ',
      location: 'HITEC City',
      address: 'Madhapur, Hitech City',
      city: 'Hyderabad',
      state: 'Telangana',
      pincode: '500081',
      type: 'commercial',
      totalUnits: 900,
      unitsAvailable: 387,
      unitPrice: 88000,
      rentalData: { expectedYield: 10.8, occupancyRate: 95, rentalIncome: 84240000 },
      expectedYield: 10.8,
      occupancyRate: 95,
      status: 'active',
      description: 'Premium tech park at the heart of Hyderabad\'s IT corridor.',
      amenities: ['Data Centre Ready', 'Auditorium', 'Food Court', 'ATM', 'Gym'],
      images: [],
      documents: { termsUrl: '/docs/terms.pdf', prospectusUrl: '/docs/prospectus.pdf', riskDisclosureUrl: '/docs/risk.pdf' },
      createdBy: 'developer-2',
    },
    {
      name: 'Mahindra World City',
      symbol: 'MHWC',
      location: 'Chengalpattu',
      address: 'NH 45, Natham Sub PO',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '603004',
      type: 'industrial',
      totalUnits: 1500,
      unitsAvailable: 678,
      unitPrice: 35000,
      rentalData: { expectedYield: 12.4, occupancyRate: 92, rentalIncome: 60900000 },
      expectedYield: 12.4,
      occupancyRate: 92,
      status: 'active',
      description: 'Integrated business city with manufacturing, IT, and logistics zones.',
      amenities: ['SEZ Zone', 'Port Connectivity', 'Rail Link', 'Township', 'Utilities'],
      images: [],
      documents: { termsUrl: '/docs/terms.pdf', prospectusUrl: '/docs/prospectus.pdf', riskDisclosureUrl: '/docs/risk.pdf' },
      createdBy: 'developer-3',
    },
    {
      name: 'Navi Mumbai SEZ',
      symbol: 'NMSZ',
      location: 'Ulwe',
      address: 'Sector 11, Ulwe Node',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '410206',
      type: 'industrial',
      totalUnits: 2500,
      unitsAvailable: 1100,
      unitPrice: 48500,
      rentalData: { expectedYield: 13.1, occupancyRate: 89, rentalIncome: 158200000 },
      expectedYield: 13.1,
      occupancyRate: 89,
      status: 'active',
      description: 'Strategic SEZ near Navi Mumbai International Airport — upcoming growth zone.',
      amenities: ['SEZ Benefits', 'Airport Proximity', 'Metro Connectivity', 'Warehousing', 'Cold Chain'],
      images: [],
      documents: { termsUrl: '/docs/terms.pdf', prospectusUrl: '/docs/prospectus.pdf', riskDisclosureUrl: '/docs/risk.pdf' },
      createdBy: 'developer-3',
    },
  ]

  PROPERTY_DATA.forEach((p, i) => {
    const id = `prop-${i + 1}`
    const history = generatePriceHistory(p.unitPrice, 12)
    const currentPrice = history[history.length - 1].price
    const prevDayPrice = history[history.length - 2]?.price ?? currentPrice

    const property: Property = {
      ...p,
      id,
      marketData: {
        currentPrice,
        prevDayPrice,
        change: currentPrice - prevDayPrice,
        changePct: ((currentPrice - prevDayPrice) / prevDayPrice) * 100,
        weekHigh: Math.max(...history.slice(-7).map(h => h.price)),
        weekLow: Math.min(...history.slice(-7).map(h => h.price)),
        yearHigh: Math.max(...history.map(h => h.price)),
        yearLow: Math.min(...history.map(h => h.price)),
        volume: Math.floor(Math.random() * 5000) + 500,
        marketCap: currentPrice * p.totalUnits,
        priceHistory: history,
      },
      listedAt: new Date(Date.now() - (30 + i * 7) * 24 * 3600 * 1000),
      lastUpdated: new Date(),
    }
    propertiesStore.set(id, property)
  })
}
